development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: reading-progress_development
  pool:     5
  username: reading-progress
  password: reading-progress
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: reading-progress_test
  pool:     5
  username: reading-progress
  password: reading-progress
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: reading-progress_production
  pool:     5
  username: reading-progress
  password: reading-progress
  template: template0
